export const ENV = {
  DATABASE_URL: 'DATABASE_URL',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  OAUTH_USER: 'OAUTH_USER',
  OAUTH_CLIENT_ID: 'OAUTH_CLIENT_ID',
  OAUTH_CLIENT_SECRET: 'OAUTH_CLIENT_SECRET',
  OAUTH_REFRESH_TOKEN: 'OAUTH_REFRESH_TOKEN',
} as const;
