export const ENV = {
  // db
  DATABASE_URL: 'DATABASE_URL',

  // jwt
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_REGISTER_SECRET: 'JWT_REGISTER_SECRET',

  // Oauth
  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_CLIENT_PW: 'KAKAO_CLIENT_PW',
  CALLBACK_URL: 'CALLBACK_URL',

  // url
  DOMAIN: 'DOMAIN',
  FRONT_URL: 'FRONT_URL',

  // s3
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION: 'AWS_REGION',
} as const;
