export const ENV = {
  // db
  DATABASE_URL: 'DATABASE_URL',

  // jwt
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',

  // Oauth
  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_CLIENT_PW: 'KAKAO_CLIENT_PW',
  CALLBACK_URL: 'CALLBACK_URL',
} as const;
