on:
  push:
    branches: [ 'master ]
    paths: 
        - 'apps/client/**'
        - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    
steps:    
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: [16.x]

- name: Installing dependencies
  run: yarn install
      
- name: Building the Application
  run: yarn build
    
- name: Upload to S3
  uses: jakejarvis/s3-sync-action@v0.5.0
  with:
    args: --acl public-read --follow-symlinks --delete
  env:
    AWS_S3_BUCKET: hello-client-s3
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'ap-northeast-2'
    SOURCE_DIR: './'

