on:
  push:
    branches: [ master ]
    paths: 'apps/admin/**'

jobs:
  deploy:
    name: HELLO_ADMIN_CD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name : .env setting
      run: |
          touch .env
          echo "${{ secrets.DATA_FOR_ENV }}" >> .env
          cat .env

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{secrets.AWS_ECR_REGISTRY_ADMIN}}
        ECR_REPOSITORY: hello-admin
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY:$IMAGE_TAG -f AdminDockerfile .
        docker push $ECR_REGISTRY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
    - name: Download Task Definition Template
      run: |
        aws ecs describe-task-definition \
          --cluster hello-gsm \
          --tasks arn:aws:ecs:ap-northeast-2:030783040786:task-definition/hellogsm-admin-task:2 \
          --query taskDefinition \
          > task-definition.json
          
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: hello-gsm-admin-container	
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: admin-task-definition.json
        service: hello-gsm-admin-service
        cluster: hello-gsm
        wait-for-service-stability: true
        
    - name: Hello, GSM Admin Server CD Success!
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: Hello-GSM Server CD Success
        color: 04CF5C

    - name: Hello, GSM Admin Server CD Failed
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: Hello-GSM Server CD Failed
        color: DC3545
