# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nestjs CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test unit
        run: yarn test 

      - name: build
        run: yarn build 
        
        
      - name: Hello, GSM Client Server CI Success!
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.CI_DISCORD_WEBHOOK }}
          title: Hello-GSM Server CI Success
          color: 04CF5C

      - name: Hello, GSM Client Server CI Failed
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.CI_DISCORD_WEBHOOK }}
          title: Hello-GSM Server CI Failed
          color: DC3545
